module.exports = {
  NODE_ENV: 'dev',
  PORT: process.env.PORT,
  MONGODB_CONNECTION_STRING: process.env.MONGODB_CONNECTION_STRING,
  MONGODB_CONNECTION_STRING_LOCAL: process.env.MONGODB_CONNECTION_STRING_LOCAL,
  AXIOS_BASE_URL: process.env.AXIOS_BASE_URL
}
